# ADD HOME parent path
HOME: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/

seed: 0
exp_name: clinical

device:
  cuda_device: cuda:0
  gpu_num_workers: 16

data:
  data_file: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/data/processed/clinical_data_test.csv
  #data_file: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/data/processed/clinical_data.csv #clinical_data_test.xlsx
  fold_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/data/processed/folds
  model_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/models
  report_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/reports
  y_label: Prognosis
  classes:
    - MILD
    - SEVERE
  batch_size: 16

model:
  model_name: mlp_1
  freeze: False

trainer:
  optimizer:
    lr: 0.001
  scheduler:
    mode: min
    patience: 5
  early_stopping: 25
  max_epochs: 300
