seed: 0
exp_name: img

device:
  cuda_device: cuda:2
  gpu_num_workers: 16

data:
  img_dir: ../data/AIforCOVID
  fold_dir: ./data/processed/folds
  mask_file:
  mask_dir:
  box_file: ./data/processed/data.xlsx #data_test.xlsx
  clahe: True
  model_dir: ./models
  report_dir: ./reports
  classes:
    - MILD
    - SEVERE
  img_dim: 224
  batch_size: 16

model:
  model_list:
    - alexnet
    - vgg11
    - vgg11_bn
    - vgg13
    - vgg13_bn
    - vgg16
    - vgg16_bn
    - vgg19
    - vgg19_bn
    - resnet18
    - resnet34
    - resnet50
    - resnet101
    - resnet152
    - resnext50_32x4d
    - resnext101_32x8d
    - wide_resnet50_2
    - wide_resnet101_2
    - densenet121
    - densenet169
    - densenet161
    - densenet201
    - googlenet
    - shufflenet_v2_x0_5
    - shufflenet_v2_x1_0
    - shufflenet_v2_x1_5
    - shufflenet_v2_x2_0
    - mobilenet_v2
    - mnasnet0_5
    - mnasnet1_0
  freeze: False
  pretrained: True

trainer:
  optimizer:
    lr: 0.001
  scheduler:
    mode: min
    patience: 5
  early_stopping: 25
  max_epochs: 300

linear:
  model_dir: ./models/linear
