# ADD HOME parent path
HOME: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/

seed: 0
exp_name: multimodal

mode_cfg:
  mode_1: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/configs/img.yaml
  mode_2: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/configs/clinical.yaml

device:
  cuda_device: cuda:0
  gpu_num_workers: 16

data:
  fold_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/data/processed/folds
  model_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/models
  report_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/reports
  classes:
    - MILD
    - SEVERE
  batch_size: 16

model:
  model_names:
    mode_1:
      model_1: densenet121
      model_2: vgg11_bn
    mode_2:
      model_1: mlp_1

trainer:
  optimizer:
    lr: 0.001
  scheduler:
    mode: min
    patience: 5
  early_stopping: 25
  max_epochs: 300

linear:
  model_dir: /home/abiricz/ai4covid_winners/COVIDCXRChallenge/models/linear
